"""empty message

Revision ID: 473ef6446d8c
Revises: 577763aa58f8
Create Date: 2024-04-17 18:45:19.703512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473ef6446d8c'
down_revision = '577763aa58f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artwork',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('medium', sa.String(), nullable=False),
    sa.Column('artist', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstname', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('lastname')
        batch_op.drop_column('firstname')

    op.drop_table('artwork')
    # ### end Alembic commands ###
